//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace CC.Core.Errors
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public  class Errors {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("CrossCuttingConcern.Core.Errors.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed, wrong Email or ApiKey.
        /// </summary>
        public static string AuthenticationFailedWrongEmailApiKey {
            get {
                return ResourceManager.GetString("AuthenticationFailedWrongEmailApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client have not access granted to the requested service.
        /// </summary>
        public static string ClientApplicationAuthorizationDeniedToService {
            get {
                return ResourceManager.GetString("ClientApplicationAuthorizationDeniedToService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItStaff doesn&apos;t exist.
        /// </summary>
        public static string ItStaffNotExist {
            get {
                return ResourceManager.GetString("ItStaffNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested module is already active.
        /// </summary>
        public static string ModuleAlreadyActive {
            get {
                return ResourceManager.GetString("ModuleAlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This module is already deactivated.
        /// </summary>
        public static string ModuleAlreadyDeactived {
            get {
                return ResourceManager.GetString("ModuleAlreadyDeactived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another existing module already use the same identification id provided.
        /// </summary>
        public static string ModuleDuplicatedById {
            get {
                return ResourceManager.GetString("ModuleDuplicatedById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module doesn&apos;t exist.
        /// </summary>
        public static string ModuleNotExist {
            get {
                return ResourceManager.GetString("ModuleNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module doesn&apos;t exist or isn&apos;t Deactivated.
        /// </summary>
        public static string ModuleNotExistOrDeactivated {
            get {
                return ResourceManager.GetString("ModuleNotExistOrDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested service doesn&apos;t exist.
        /// </summary>
        public static string RequestedServiceNotExist {
            get {
                return ResourceManager.GetString("RequestedServiceNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service is activated.
        /// </summary>
        public static string ServiceActivated {
            get {
                return ResourceManager.GetString("ServiceActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service is deactivated.
        /// </summary>
        public static string ServiceDeactivated {
            get {
                return ResourceManager.GetString("ServiceDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio no puede ser activado porque el modulo esta desactivado o porque no se a asignado el servicio a un modulo.
        /// </summary>
        public static string ServiceNotActivatedModuleDeactivated {
            get {
                return ResourceManager.GetString("ServiceNotActivatedModuleDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service doesn&apos;t exist.
        /// </summary>
        public static string ServiceNotExist {
            get {
                return ResourceManager.GetString("ServiceNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service doesn&apos;t exist or is Deactivated.
        /// </summary>
        public static string ServiceNotExistOrDeactivated {
            get {
                return ResourceManager.GetString("ServiceNotExistOrDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service doesn&apos;t exist or isn&apos;t activated.
        /// </summary>
        public static string ServiceNotExistOrNotActivated {
            get {
                return ResourceManager.GetString("ServiceNotExistOrNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service doesn&apos;t exist or isn&apos;t deactivated.
        /// </summary>
        public static string ServiceNotExistOrNotDeactivated {
            get {
                return ResourceManager.GetString("ServiceNotExistOrNotDeactivated", resourceCulture);
            }
        }
        /// <summary>
        /// Agencia actualizada
        /// </summary>
        public static string AgenciaActualizada {
            get {
                return ResourceManager.GetString("AgenciaActualizada", resourceCulture);
            }
        }
        /// <summary>
        /// Agencia Existe
        /// </summary>
        public static string CategoriaExiste {
            get {
                return ResourceManager.GetString("CategoriaExiste", resourceCulture);
            }
        }
    }
}
